apply from: 'versions.gradle'

buildscript {
    repositories {
        mavenLocal()
        maven {
            url "https://mirrors.cloud.tencent.com/nexus/repository/maven-public"
        }
        mavenCentral()
        google()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.10'
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            url "https://mirrors.cloud.tencent.com/nexus/repository/maven-public"
        }
        mavenCentral()
        google()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.getLayout().getBuildDirectory()
}
