ext {

    /**
     * android config
     */
    config = [
            compileSdkVersion: 35,
            minSdkVersion    : 23,
            targetSdkVersion : 35,
    ]

    versions = [
            design              :   '28.0.0',
            appcompat           :   '1.1.0',
            startup             :   '1.0.0',
            material            :   '1.1.0',
            constraintlayout    :   '1.1.3',
            swiperefreshlayout  :   '1.1.0',
            desugar_jdk_libs    :   '1.0.9',
            dagger              :   '2.35.1',
            retrofit            :   '2.9.0',
            gson                :   '2.8.5',
            ok_logging          :   '3.5.0',
            converter_gson      :   '2.0.1',
            rxjava3             :   '3.0.3',
            rxandroid           :   '3.0.0',
            glide               :   '4.14.2',
    ]
}