apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'project-report'
apply from: '../versions.gradle'
apply from: '../graver.gradle'

android {
    namespace 'com.github'
    compileSdk rootProject.ext.config.compileSdkVersion
    defaultConfig {
        applicationId "com.github.android.pro"
        minSdkVersion rootProject.ext.config.minSdkVersion
        targetSdkVersion rootProject.ext.config.targetSdkVersion
        versionCode 1
        versionName "0.0.1"
        buildConfigField "long", "BUILD", getBuildTime() + "L"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        renderscriptTargetApi 18
        renderscriptSupportModeEnabled true
        multiDexEnabled true
        manifestPlaceholders = [APP_NAME: "Github"]
    }

    buildFeatures {
        dataBinding true
        buildConfig true
        renderScript true
    }

    sourceSets {
        main {
            res.srcDirs = [
                    'src/main/res',
                    'src/main/res/base',
                    'src/main/res/feed'
            ]
            jniLibs.srcDirs = ['libs']
        }

        debug {
            res.srcDirs = [
                    'src/debug/res',
            ]
            jniLibs.srcDirs = ['libs']
            java.srcDirs = ['src/debug/java']
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            matchingFallbacks = ['release']
        }
    }

    productFlavors {
        alpha {
            flavorDimensions "main"
            versionName version + "-alpha"
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        incremental true
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    dependenciesInfo {
        includeInApk false
        includeInBundle false
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

}

configurations.configureEach {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'org.jetbrains.kotlin') {
            details.useVersion '2.2.10'
        }
    }
}

dependencies {
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:$versions.desugar_jdk_libs"

    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(":library")
    implementation project(":appmock")

    // vault
    implementation project(":vault")
    implementation project(":vault-datastore")
    implementation project(":vault-mmkv")
    implementation 'com.tencent:mmkv:2.4.1'

    implementation "androidx.appcompat:appcompat:$versions.appcompat"
    implementation "androidx.constraintlayout:constraintlayout:$versions.constraintlayout"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:$versions.swiperefreshlayout"
    implementation "androidx.startup:startup-runtime:$versions.startup"

    implementation "com.google.code.gson:gson:$versions.gson"
    implementation "com.google.android.material:material:$versions.material"
    implementation "com.google.dagger:dagger:$versions.dagger"
    implementation "com.google.dagger:dagger-android:$versions.dagger"
    implementation "com.google.dagger:dagger-android-support:$versions.dagger"
    kapt "com.google.dagger:dagger-compiler:$versions.dagger"
    kapt "com.google.dagger:dagger-android-processor:$versions.dagger"

    implementation "com.squareup.retrofit2:adapter-rxjava3:2.9.0"
    implementation "com.squareup.retrofit2:retrofit:$versions.retrofit"
    implementation "com.squareup.okhttp3:logging-interceptor:$versions.ok_logging"
    implementation "com.squareup.retrofit2:converter-gson:$versions.converter_gson"
    implementation "io.reactivex.rxjava3:rxjava:$versions.rxjava3"
    implementation "io.reactivex.rxjava3:rxandroid:$versions.rxandroid"
    implementation "com.github.bumptech.glide:glide:$versions.glide"
    kapt "com.github.bumptech.glide:compiler:$versions.glide"

    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.robolectric:robolectric:4.9'
}